[project]
name = "incident-tracker-ucar-topdoer"
version = "0.1.0"
description = "Incident tracker API using Django + DRF + PostgreSQL"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [{ name = "Topdoer Candidate" }]
dependencies = [
    "Django>=5.2,<5.3",
    "djangorestframework>=3.16,<3.17",
    "drf-spectacular[sidecar]>=0.27,<0.28",
    "psycopg2-binary>=2.9,<3.0",
    "python-dotenv>=1.0,<2.0",
]

[tool.uv]
package = true

index-strategy = "unsafe-best-match"
default-groups = ["dev"]

[dependency-groups]
dev = [
    "pytest>=8.0,<9.0",
    "pytest-django>=4.8,<5.0",
    "pre-commit>=3.8,<4.0",
    "ruff>=0.6,<0.7",
    "black>=24.8,<25.0"
]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
lint.select = ["E", "F", "I", "UP", "B"]
lint.ignore = []
format.quote-style = "double"
